spring:
## PostgreSQL
  datasource:
    url: "jdbc:postgresql://localhost:5432/dexterity"
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
## Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
## Web
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
  thymeleaf:
    cache: false

## DDL
jpa:
  hibernate:
    ddl-auto: none

## Server
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

## Properties
upload:
  path: src/main/resources/static/images/
  apath: src\main\resources\static\images