spring:
## PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/dexterity
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
## Web
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none

## Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

## Server
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

## Properties
upload:
  imagesPath: res/images/

compileta:
  compileUrl: http://localhost:8081/compile
  compileAllUrl: http://localhost:8081/compile_all
